const words = [
  { 
    en: "Quantity", 
    cn: "量", 
    enUsage: "Represents the magnitude of a physical quantity", 
    usage:"表示物理量的大小或数值，不涉及方向。", 
    tags: ["Physics"], 
    formula:"", 
    category:"Scalar", 
    similar:["Distance","Speed",], 
    example:"质量、长度、时间",
    updated: "2025-12-28"
  },
  { 
    en: "Speed", 
    cn: "速率", 
    enUsage: "Rate at which an object is moving. Does not depend on direction.", 
    usage:"表示物体运动快慢的量，不包含方向。", 
    tags: ["Physics"], 
    formula:"s = d/t", 
    category:"Scalar", 
    similar:["Distance","Velocity",], 
    example:"汽车行驶速度、风速",
    updated: "2025-12-28"
  },
  { 
    en: "Velocity", 
    cn: "速度", 
    enUsage: "Speed with direction. Has magnitude and direction.", 
    usage:"具有大小和方向的速度，是一个向量。", 
    tags: ["Physics"], 
    formula:"v = s/t", 
    category:"Vector", 
    similar:["Displacement","Speed",], 
    example:"向北10 ms¯¹" ,
    updated: "2025-12-28"
  },
  { 
    en: "Vector", 
    cn: "向量", 
    enUsage: "Represents a quantity with both magnitude and direction", 
    usage:"表示同时具有大小和方向的物理量。", 
    tags: ["Physics","Math"], 
    formula:"", 
    category:"Vector", 
    similar:["Acceleration","Displacement","Velocity",], 
    example:"力、速度" ,
    updated: "2025-12-28"
  },
  {
    en: "Scalar", 
    cn: "标量", 
    enUsage: "A quantity that only has magnitude without direction", 
    usage:"只有大小、没有方向的物理量。", 
    tags: ["Physics","Math"], 
    formula:"", 
    category:"Scalar", 
    similar:["Distance","Magnitude",], 
    example:"温度、质量" ,
    updated: "2025-12-28"
  },
  { 
    en: "Magnitude", 
    cn: "大小", 
    enUsage: "A measure that has a value", 
    usage:"表示一个量的数值大小，不包含方向信息。", 
    tags: ["Physics","Math"], 
    formula:"", 
    category:"Scalar", 
    similar:["Scalar","Vector"], 
    example:"速度的大小、力的大小" ,
    updated: "2025-12-28"
  },
  { 
    en: "Acceleration", 
    cn: "加速", 
    enUsage: "Change in velocity over time", 
    usage:"单位时间内速度的变化量，是一个向量。", 
    tags: ["Physics"], 
    formula:"a = Δv/t", 
    category:"Vector", 
    similar:["Speed","Velocity",], 
    example:"自由落体加速度 9.8 ms⁻²" ,
    updated: "2025-12-28"
  },
  { 
    en: "Trigonometric Function", 
    cn: "三角函数", 
    enUsage: "Functions like sine, cosine, tangent", 
    usage:"用于描述角度与边长关系的函数，如正弦、余弦、正切等。", 
    tags: ["Math"], 
    formula:"", 
    category:"Function", 
    similar:["Pythagorean Theorem"], 
    example:"sin(30°)=0.5, cos(60°)=0.5" ,
    updated: "2025-12-28"
  },
  { 
    en: "Pythagorean Theorem", 
    cn: "毕氏定理", 
    enUsage: "Relation between the sides of a right triangle", 
    usage:"描述直角三角形三边长度关系的定理。", 
    tags: ["Math"], 
    formula:"a² + b² = c²", 
    category:"Theorem", 
    similar:["Trigonometric Function"], 
    example:"直角三角形，a=3, b=4, c=5" ,
    updated: "2025-12-28"
  },
  { 
    en: "Pure Substance", 
    cn: "纯净物", 
    enUsage: "Made up of only one kind of particles", 
    usage:"由单一成分组成的物质。", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"Substance", 
    similar:["Mixture"], 
  classification: [
    { en: "Element", cn: "单质" },
    { en: "Compound", cn: "化合物" }
  ],
    example:"水、氧气" ,
    updated: "2025-12-29"
  },
  { 
    en: "Mixture", 
    cn: "混合物", 
    enUsage: "Made up of two or more substances, not chemically combined, can be separated by physical means", 
    usage:"由两种或两种以上物质组成，不通过化学方式结合，可以通过物理方法分离。", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"Substance", 
    similar:["Pure Substance"], 
    classification: [
      { en: "Heterogeneous Mixture", cn: "非均相混合物" },
      { en: "Homogeneous Mixture", cn: "均相混合物" },
    ],
    example:"空气、盐水" ,
    updated: "2025-12-29"
  },
  { 
    en: "Distance", 
    cn: "距离", 
    enUsage: "How far an object travels, does not depend on direction", 
    usage:"物体实际运动路径的总长度，不包含方向。", 
    tags: ["Physics"], 
    formula:"s = v × t", 
    category:"Scalar", 
    similar:["Displacement","Speed"], 
    example:"The ant walked 1cm" ,
    updated: "2025-12-28"
  },
  { 
    en: "Displacement", 
    cn: "位移", 
    enUsage: "Difference between an object's final and its starting position, does depend on direction", 
    usage:"物体实际运动路径的总长度，与方向无关。", 
    tags: ["Physics"], 
    formula:"Δx = x₂ - x₁", 
    category:"Vector", 
    similar:["Distance","Velocity"], 
    example:"The ant walked 3cm East" ,
    updated: "2025-12-28"
  },
  { 
    en: "Constant", 
    cn: "常数", 
    enUsage: "A fixed numerical value", 
    usage:"数值固定不变的量", 
    tags: ["Math","Physics"], 
    formula:"", 
    category:"Scalar", 
    similar:["Magnitude","Quantity",], 
    example:"π=3.14159, 重力加速度 g=9.8 ms¯²" ,
    updated: "2025-12-28"
  },
  { 
    en: "Compound", 
    cn: "化合物", 
    enUsage: "Consist of two or more elements chemically bonded together, have completely new properties", 
    usage:"由两种或两种以上元素通过化学键合而成，有新物质产生。", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"Substance", 
    similar:["Element"], 
    classification: [
      { en: "Covalent", cn: "共价化合物" },
      { en: "Ionic", cn: "离子化合物" },
    ],
    example:"NaCI, H₂O" ,
    updated: "2025-12-29"
  },
  { 
    en: "Element", 
    cn: "单质", 
    enUsage: "Consist of only one kind of atom/molecule, cannot be separated into simpler substances", 
    usage:"仅由一种原子/分子构成，不能被分解。", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"Pure Substance", 
    similar:["Compound"], 
    classification: [
      { en: "Atoms", cn: "原子" },
      { en: "Molecules", cn: "分子" },
    ],
    example:"Gold, Argon gas" ,
    updated: "2025-01-14"
  },
  { 
    en: "Particle", 
    cn: "粒子", 
    enUsage: "Matter is made of particles", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:[""], 
    classification: [
      { en: "Ions", cn: "离子"},
      { en: "Atoms", cn: "原子"},
      { en: " Molecules", cn: "分子"},
    ],
    example:"" ,
    updated: "2025-12-29"
  },
  { 
    en: "Atoms", 
    cn: "原子", 
    enUsage: "Smallest neutral particle of an element, can exist on its own", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"Element", 
    similar:["Molecules"], 
    example:"He, Ne, Ar" ,
    updated: "2025-12-29"
  },
  { 
    en: "Molecules", 
    cn: "分子", 
    enUsage: "Two or more atoms chemically bonded", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"Element", 
    similar:["Atoms"], 
    example:"H₂, O₂, CO₂" ,
    updated: "2025-12-29"
  },
  { 
    en: "Ions", 
    cn: "离子", 
    enUsage: "When atoms lose or gain electrons, they become charge particles", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:[""], 
    classification: [
    { en: "Cation", cn: "阳离子" },
    { en: "Anion", cn: "阴离子" }
  ],
    example:"" ,
    updated: "2025-12-29"
  },
  { 
    en: "Matter", 
    cn: "物质", 
    enUsage: "Matter is anything that has mass and occupies space. All physical objects are matter.", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["","",], 
    classification: [
      { en: "Pure Substance", cn: "纯净物" },
      { en: "Mixture", cn: "混合物" },
    ],
    example:"",
    updated: "2026-01-14"
  },
  { 
    en: "Covalent", 
    cn: "共价化合物", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Ionic",], 
    example:"Water",
    updated: "2026-01-14"
  },
  { 
    en: "Ionic", 
    cn: "离子化合物", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Covalent",], 
    example:"Sodium Chloride",
    updated: "2026-01-14"
  },
  { 
    en: "Solid", 
    cn: "固体", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Liquid","Gas",], 
    example:"Ice",
    updated: "2026-01-15"
  },
  { 
    en: "Liquid", 
    cn: "液体", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Solid","Gas",], 
    example:"Water",
    updated: "2026-01-15"
  },
  { 
    en: "Gas", 
    cn: "气体", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Solid","Liquid",], 
    example:"Steam",
    updated: "2026-01-15"
  },
  { 
    en: "Heterogeneous Mixture", 
    cn: "非均相混合物", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Homogeneous Mixture",], 
    example:"",
    updated: "2026-01-14"
  },
  { 
    en: "Homogeneous Mixture", 
    cn: "均相混合物", 
    enUsage: "", 
    usage:"", 
    tags: ["Chemistry"], 
    formula:"", 
    category:"", 
    similar:["Heterogeneous Mixture",], 
    example:"",
    updated: "2026-01-14"
  },
];
